"""empty message

Revision ID: ed6eda5417d6
Revises: 
Create Date: 2024-12-27 17:33:39.096929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed6eda5417d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_license_report', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('license_id',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=128),
               existing_comment='许可证编号',
               existing_nullable=True)
        batch_op.alter_column('issuance_time',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=128),
               comment='颁发时间',
               existing_comment='发证时间',
               existing_nullable=True)
        batch_op.alter_column('license_company',
               existing_type=mysql.VARCHAR(length=500),
               comment='许可证公司',
               existing_comment='授权公司',
               existing_nullable=True)
        batch_op.alter_column('tax_identification_number',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Integer(),
               existing_comment='纳税人识别号',
               existing_nullable=True)
        batch_op.alter_column('factory_registration_number',
               existing_type=mysql.VARCHAR(length=500),
               comment='注册登记编号',
               existing_comment='注册编号',
               existing_nullable=True)
        batch_op.alter_column('factory_address',
               existing_type=mysql.VARCHAR(length=500),
               comment='注册登记编号',
               existing_comment='注册地址',
               existing_nullable=True)
        batch_op.create_unique_constraint('license_id_unique', ['license_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_license_report', schema=None) as batch_op:
        batch_op.drop_constraint('license_id_unique', type_='unique')
        batch_op.alter_column('factory_address',
               existing_type=mysql.VARCHAR(length=500),
               comment='注册地址',
               existing_comment='注册登记编号',
               existing_nullable=True)
        batch_op.alter_column('factory_registration_number',
               existing_type=mysql.VARCHAR(length=500),
               comment='注册编号',
               existing_comment='注册登记编号',
               existing_nullable=True)
        batch_op.alter_column('tax_identification_number',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=500),
               existing_comment='纳税人识别号',
               existing_nullable=True)
        batch_op.alter_column('license_company',
               existing_type=mysql.VARCHAR(length=500),
               comment='授权公司',
               existing_comment='许可证公司',
               existing_nullable=True)
        batch_op.alter_column('issuance_time',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=500),
               comment='发证时间',
               existing_comment='颁发时间',
               existing_nullable=True)
        batch_op.alter_column('license_id',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=500),
               existing_comment='许可证编号',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
